### ISSUE TITLE
add posibility to make user `superuser`

### ISSUE THREAD

**Issue by crchemist** [crchemist/cit#41]
- add is_superuser to User model.
- protect /admin/ is accessible only by for which is_superuser=true.

**Comment by zimoham** [comment]
+

**Comment by crchemist** [comment]
should be implemented like:
http://flask-admin.readthedocs.org/en/v1.0.9/quickstart/#authentication

BTW our user is stored as:

```
g.user.is_superuser
```

**Comment by bubanoid** [comment]
I take it
